
language: rust
sudo: required
dist: trusty
cache: cargo
rust:
  - stable
  - beta
  - nightly

addons:
  postgresql: '9.5'

script:
- |
  ./test_setup.sh "$TRAVIS_RUST_VERSION"
  cargo build
  cargo test
  if [[ "$TRAVIS_RUST_VERSION" == nightly* ]]; then
    cargo clippy
  fi

env:
  global:
    - RUST_TEST_THREADS=1
