
language: rust
sudo: required
dist: trusty
cache: cargo
rust:
  - beta
  - nightly

addons:
  postgresql: '9.5'

script:
- |
  ./test_setup.sh
  cargo build
  cargo test
  cargo clippy

env:
  global:
    - RUST_TEST_THREADS=1
