
language: rust
sudo: required
dist: trusty
cache: cargo
rust:
  - nightly

addons:
  postgresql: '9.5'

script:
- |
  chmod +x test_setup.sh
  ./test_setup.sh
  cargo clippy
  cargo test --all-features --all
