
language: rust
sudo: required
dist: trusty
cache: cargo
rust:
  - beta
  - nightly

addons:
  postgresql: '9.5'

before_script:
- |
  export PATH=$HOME/.local/bin:$PATH
  ./test_setup.sh

script:
- |
  cargo build &&
  cargo test &&

after_success:
  - travis-cargo coveralls --verify

env:
  global:
    - RUST_TEST_THREADS=1
